services:
  db:
    image: postgres:17-alpine
    container_name: postgres17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
      POSTGRES_DB: ${DB__NAME}
    ports:
      - "${DB__PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  qa_backend:
    build:
      dockerfile: Dockerfile
    container_name: qa_backend
    working_dir: /app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped


volumes:
  postgres_data: